name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      # ---- SAFE INSTALL SECTION ----
      # If this is a PR from a fork, run a safer install that ignores lifecycle scripts.
      - name: Install dependencies (safe mode for forks)
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
        run: npm ci --ignore-scripts

      # Otherwise, for trusted pushes/branches, run a normal install.
      - name: Install dependencies
        if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
        run: npm ci
      # ---- END SAFE INSTALL SECTION ----

      - name: Run linter
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Run type check
        run: npm run type-check

      - name: Run security audit
        run: npm run audit:production
        continue-on-error: true

      - name: Run tests
        run: npm run test -- --coverage

      - name: Run a11y (unit)
        run: npm run test:a11y
        continue-on-error: true

      - name: Build project
        run: npm run build

      - name: Start preview server
        run: npm run preview & # vite preview
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run a11y E2E
        run: npm run test:e2e:a11y
        continue-on-error: true

      - name: Upload coverage to Codecov (optional)
        uses: codecov/codecov-action@v3
        if: success()
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
