permissions:
  contents: read
  issues: write

name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at midnight UTC
  push:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

jobs:
  security:
    name: Dependency Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Allow the job to continue so the "Create issue" step can run conditionally
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Check for outdated packages
        run: npm outdated || true

      # Run only if some previous step failed (i.e., audit found issues)
      - name: Create issue if vulnerabilities found
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const title = '🚨 Security vulnerabilities detected';
            const body =
              'Automated security scan found vulnerabilities. Please review and update dependencies.\n\n' +
              'Run `npm audit` locally for details.';
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ['security', 'dependencies']
            });
